#!/bin/bash

clear
echo -e "================================================="
echo -e "# Script Auto Install SSH & OpenVPN             #"
echo -e "#-----------------------------------------------#"
echo -e "# For Debian 9 & 10 Buster 64 bit               #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "# Modified by Haweng                            #"
echo -e "#-----------------------------------------------#"
echo -e "# Thanks To                                     #"
echo -e "#-----------------------------------------------#"
echo -e "# HAWENG.                                       #"
echo -e "# Allah                                         #"
echo -e "# My Family                                     #"
echo -e "# Ekouble                                        #"
echo -e "# Horas Siregar                                 #"
echo -e "# hablessh.tech                                 #"
echo -e "#                                               #"
echo -e "#-----------------------------------------------#"
echo -e "================================================="
