#!/bin/bash

clear
neofetch
sleep 0.5
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━[ Autoscript Premium  ]━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e ""
echo -e "----------------------------------------------------------------------"
echo -e ""
echo -e   ">>> Service & Default Port"
echo -e   "- OpenSSH                 : 22"
echo -e   "- SSH-Websocket           : 2082"
echo -e   "- OpenVPN                 : TCP 1194, UDP 2200, SSL 442"
echo -e   "- OpenVPN-Webscoket       : TCP 2086"
echo -e   "- Stunnel4                : 443, 222,  777"
echo -e   "- Dropbear                : 109, 143"
echo -e   "- Squid Proxy             : 3128, 8080"
echo -e   "- Badvpn                  : 7100, 7200, 7300"
echo -e   "- Nginx                   : 81"
echo -e   "- Shadowsocks-R           : 1443-1543"
echo -e   "- SS-OBFS TLS             : 2443-2543"
echo -e   "- SS-OBFS HTTP            : 3443-3543"
echo -e   "- V2RAY Vmess TLS         : 8443"
echo -e   "- V2RAY Vmess None TLS    : 80"
echo -e   "- V2RAY Vless TLS         : 2083"
echo -e   "- V2RAY Vless None TLS    : 8880"
echo -e   "- Trojan                  : 2087"
echo -e ""                                                                                
echo -e   ">>> Server Information & Other Features"
echo -e   "- Timezone                : Asia/Jakarta (GMT +7)"
echo -e   "- Fail2Ban                : [ON]"
echo -e   "- Dflate                  : [ON]"
echo -e   "- IPtables                : [ON]"
echo -e   "- Auto-Reboot             : [ON]"
echo -e   "- IPv6                    : [OFF]"
echo -e   "- Autoreboot On 05.00 GMT +7"
echo -e   "- Auto Delete Expired Account"
echo -e   "- Full Orders For Various Services"
echo -e   "- White Label"
echo -e   "- Installation Log --> /root/log-install.txt"
echo -e ""
echo -e "----------------------------->Dev/Main<------------------------------"
echo -e   "- Build Up                : By Haweng"
echo -e   "- Telegram                : t.me/omaigatt_ikan"
echo -e   "- Whatsapp                : wa.me/6281226026313"
echo -e   "- WEB SSH                 : https://hablessh.tech"
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━[ Autoscript Premium ]━━━━━━━━━━━━━━━━━━━━━━━"
echo -e ""
